import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type RepoResult = {
  fullName: string;
  url: string;
  description: string | null;
  stars: number;
  language: string | null;
  defaultBranch: string;
  pushedAt: string | null;
  updatedAt: string | null;
  files: Array<{ path: string; url: string }>;
};

type StaticData = {
  generatedAt: string | null;
  query: string;
  totalCount: number;
  incompleteResults: boolean;
  repositoryCount: number;
  repositories: RepoResult[];
};

type SortMode = 'stars-desc' | 'stars-asc' | 'name-asc' | 'updated-desc';

function formatDate(value: string | null) {
  if (!value) return 'unknown';
  return new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(value));
}

function App() {
  const [data, setData] = useState<StaticData | null>(null);
  const [language, setLanguage] = useState('all');
  const [sortMode, setSortMode] = useState<SortMode>('stars-desc');
  const [textFilter, setTextFilter] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/repositories.json`, { cache: 'no-cache' })
      .then((response) => {
        if (!response.ok) throw new Error(`Failed to load data: ${response.status}`);
        return response.json() as Promise<StaticData>;
      })
      .then(setData)
      .catch((caught) => setError(caught instanceof Error ? caught.message : String(caught)));
  }, []);

  const repositories = data?.repositories ?? [];

  const languages = useMemo(() => {
    const values = new Set(repositories.map((repo) => repo.language).filter((value): value is string => Boolean(value)));
    return Array.from(values).sort((a, b) => a.localeCompare(b));
  }, [repositories]);

  const visibleRepos = useMemo(() => {
    const normalizedFilter = textFilter.trim().toLowerCase();
    const filtered = repositories.filter((repo) => {
      const languageMatches = language === 'all' || repo.language === language;
      const textMatches =
        !normalizedFilter ||
        repo.fullName.toLowerCase().includes(normalizedFilter) ||
        (repo.description ?? '').toLowerCase().includes(normalizedFilter);
      return languageMatches && textMatches;
    });

    return [...filtered].sort((a, b) => {
      if (sortMode === 'stars-asc') return a.stars - b.stars;
      if (sortMode === 'name-asc') return a.fullName.localeCompare(b.fullName);
      if (sortMode === 'updated-desc') {
        return new Date(b.updatedAt ?? 0).getTime() - new Date(a.updatedAt ?? 0).getTime();
      }
      return b.stars - a.stars;
    });
  }, [language, repositories, sortMode, textFilter]);

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">GitHub Actions security discovery</p>
        <h1>Repositories using <code>pull_request_target</code></h1>
        <p>
          A static index generated by GitHub Actions. Browse repositories whose workflow files contain
          <code>pull_request_target</code>, sort by stars, and filter by primary language without entering a token.
        </p>
      </section>

      {error ? <div className="panel error"><strong>Data load failed.</strong><br />{error}</div> : null}

      <section className="panel controls" aria-label="Result controls">
        <div>
          <span className="stat">{repositories.length}</span>
          <span className="muted"> repositories indexed</span>
        </div>
        <div>
          <span className="stat">{data?.totalCount ?? '-'}</span>
          <span className="muted"> matching files reported by GitHub</span>
        </div>
        <label>
          Language
          <select value={language} onChange={(event) => setLanguage(event.target.value)}>
            <option value="all">All languages</option>
            {languages.map((value) => <option key={value} value={value}>{value}</option>)}
          </select>
        </label>
        <label>
          Sort
          <select value={sortMode} onChange={(event) => setSortMode(event.target.value as SortMode)}>
            <option value="stars-desc">Stars: high to low</option>
            <option value="stars-asc">Stars: low to high</option>
            <option value="name-asc">Name: A to Z</option>
            <option value="updated-desc">Recently updated</option>
          </select>
        </label>
        <label className="wide-field">
          Filter repositories
          <input
            placeholder="owner/name or description"
            value={textFilter}
            onChange={(event) => setTextFilter(event.target.value)}
          />
        </label>
      </section>

      <section className="panel data-note">
        <div><strong>Generated:</strong> {data?.generatedAt ? formatDate(data.generatedAt) : 'not generated yet'}</div>
        <div><strong>Query:</strong> <code>{data?.query ?? 'loading...'}</code></div>
        {data?.incompleteResults ? <div className="notice">GitHub marked the source search as incomplete.</div> : null}
      </section>

      <section className="results" aria-live="polite">
        {visibleRepos.map((repo) => (
          <article className="repo-card" key={repo.fullName}>
            <header>
              <div>
                <a className="repo-name" href={repo.url} target="_blank" rel="noreferrer">{repo.fullName}</a>
                <p>{repo.description || 'No description provided.'}</p>
              </div>
              <div className="stars" title="GitHub stars">★ {repo.stars.toLocaleString()}</div>
            </header>
            <dl className="metadata">
              <div><dt>Language</dt><dd>{repo.language || 'Unknown'}</dd></div>
              <div><dt>Default branch</dt><dd>{repo.defaultBranch}</dd></div>
              <div><dt>Last push</dt><dd>{formatDate(repo.pushedAt)}</dd></div>
            </dl>
            <details>
              <summary>{repo.files.length} matching workflow file{repo.files.length === 1 ? '' : 's'}</summary>
              <ul>
                {repo.files.map((file) => (
                  <li key={file.url}><a href={file.url} target="_blank" rel="noreferrer">{file.path}</a></li>
                ))}
              </ul>
            </details>
          </article>
        ))}
      </section>
    </main>
  );
}

createRoot(document.getElementById('root')!).render(<App />);
